### ISSUE TITLE
Babel transpilation

### ISSUE THREAD

**Issue by Turbo87** [rwjblue/ember-cli-cjs-transform#14]
This might be the wrong repo to ask this, but I'm not sure where else it would fit better: how can we handle CJS modules that were written for e.g. Node 8 and will require transpilation when being run in e.g. IE11?

**Comment by rwjblue** [comment]
I think its conceptually fine to handle here.

**Comment by kevinansfield** [comment]
I've run into the same issue, is there any workaround at the moment other than modifying the CJS module to remove ES2015 usage?

**Comment by rwjblue** [comment]
Should be possible now with the `plugins` option added in #30

**Comment by Gaurav0** [comment]
For those reading this, the plugin you're looking for is `rollup-plugin-babel`: https://github.com/rollup/rollup-plugin-babel

```js
const babel = require('rollup-plugin-babel');

app.import('node_modules/some-name/index.js', {
  using: [
    { transformation: 'cjs', as: 'some-name', plugins: [ babel({ babelrc: false }) ]}
  ]
});
```
