### ISSUE TITLE
Change the latest version of this package on the npm registry

### ISSUE THREAD

**Issue by tniezurawski** [rwjblue/ember-cli-cjs-transform#257]
When performing `npm outdated` it is stated that version `1.3.1` is the latest:

```bash
➜  npm outdated
Package				Current		Wanted		Latest
ember-cli-cjs-transform		2.0.0		2.0.0		1.3.1
```

It is this way because the npm registry sees `1.3.1` as the latest version:

![image](https://user-images.githubusercontent.com/4335166/63154222-6cdddd80-c010-11e9-9011-ab1b2f854a7c.png)

@rwjblue Is there anything we can do about it?

**Comment by rwjblue** [comment]
Thanks for reporting! Sorry about that, fixed now.
