### ISSUE TITLE
`cjs-transform` cache files in `$TMPDIR` require removal to avoid import errors

### ISSUE THREAD

**Issue by jblakeman** [rwjblue/ember-cli-cjs-transform#91]
Hi,

Periodically, we've been seeing an issue occur when running `ember s` locally in our project. The app will not load because of a fatal error "Could not find module ember-resolver". After some quick investigation, we discovered that if we remove the `cjs-transform` temporary cache directory, it fixes the problem:

```
$ find $TMPDIR -type d -name '*cjs-transform*' -exec rm -rf {} +;
```

ember-cli version: 2.16.2
ember-cli-cjs-transform version: 1.3.0
ember-resolver version: 4.5.5

**Comment by les2** [comment]
@jblakeman is `ember-cli version` the version of ember-cli inside the project? or the globally installed ember-cli ?

**Comment by les2** [comment]
@jblakeman also, do you have a way to reproduce the problem?

**Comment by jblakeman** [comment]
>is ember-cli version the version of ember-cli inside the project? or the globally installed ember-cli ?

Inside the project.

>do you have a way to reproduce the problem?

Unfortunately, no.

**Comment by buschtoens** [comment]
I'm experiencing this bug as well. It seems that _sometimes_ the transform is just not applied and the original source code, which has a `module.exports = ...` statement in it, is just concatenated into `vendor.js` as is, causing these errors:

![image](https://user-images.githubusercontent.com/834636/45415032-fce70a80-b67c-11e8-8f61-03cf75a29539.png)

The second error is caused indirectly by the first error, since `ember-resolver` is part of the `vendor.js` bundle which fails to execute.

**Comment by les2** [comment]
@buschtoens we get this problem occasionally at work.

originally, we had no clue on how to fix it other than trying lots of random things and praying.

then we discovered (these were hug discoveries):

1. restarting the computer would fix the problem
2. that made us wonder whether simply `rm -rf $TMPDIR` would work, and lo and behold it did.
3. then a clever @jblakeman discovered which subfolder in `$TMPDIR` would fix the problem and created this snippet: `find $TMPDIR -type d -name '*cjs-transform*' -exec rm -rf {} +;`

Thus, we currently believe that it is the `cjs-transform` that is responsible for the problem.

**Comment by buschtoens** [comment]
@les2 Yes, I can confirm that the fix shown in https://github.com/rwjblue/ember-cli-cjs-transform/issues/91#issue-358668852 indeed works for me:

```
find $TMPDIR -type d -name '*cjs-transform*' -exec rm -rf {} +;
```

For some weird reason we had to restart my coworkers MacBook, but on my MacBook it works reliably.

**Comment by timrwood** [comment]
We ran into this issue as well. FWIW, this usually happens on a Monday, maybe because a cache expired over the weekend?

I'm pasting the error messages here so anyone else googling for them can find this issue + workaround.

```
Uncaught ReferenceError: module is not defined
Uncaught Error: Could not find module `ember-resolver` imported from `frontend/resolver`
```

**Comment by stefanpenner** [comment]
I have a potential fix.

**Comment by stefanpenner** [comment]
fix https://github.com/rwjblue/ember-cli-cjs-transform/pull/143

**Comment by stefanpenner** [comment]
@rwjblue can you add me as a maintainer, i can help reduce the buss factor.
